import { useEffect, useMemo, useRef, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { Link, Route, Router as WouterRouter, Switch, useLocation, useRoute } from 'wouter';
import {
  ArrowDownToLine, ArrowRight, BarChart3, CarFront, Check,
  ChevronDown, CircleHelp, ClipboardList, DollarSign, Download, FileImage, Fuel,
  Gauge, LayoutDashboard, Pencil, Plus, Receipt, RotateCcw,
  Search, Settings as SettingsIcon, Trash2, Upload, X, Zap,
} from 'lucide-react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';

type Platform = 'Uber' | 'Lyft' | 'Both' | 'Personal';
type Unit = 'km' | 'mi';
type Currency = 'CAD' | 'USD';
type LogEntry = {
  id: string; date: string; startOdometer: number; endOdometer: number; distanceKm: number;
  fuelLiters: number; fuelCost: number; station: string; platform: Platform;
  odometerPhoto?: string; receiptPhoto?: string; notes: string; createdAt: string;
};
type Settings = { driverName: string; unit: Unit; currency: Currency };

const queryClient = new QueryClient();
const LOGS_KEY = 'driver-logbook-logs';
const SETTINGS_KEY = 'driver-logbook-settings';
const defaultSettings: Settings = { driverName: '', unit: 'km', currency: 'CAD' };

function useStored<T>(key: string, fallback: T) {
  const [value, setValue] = useState<T>(() => {
    try { const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) as T : fallback; } catch { return fallback; }
  });
  useEffect(() => { localStorage.setItem(key, JSON.stringify(value)); }, [key, value]);
  return [value, setValue] as const;
}

function makeId() { return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; }
function today() { return new Date().toISOString().slice(0, 10); }
function formatMoney(value: number, currency: Currency) { return new Intl.NumberFormat('en-CA', { style: 'currency', currency }).format(value); }
function displayDistance(km: number, unit: Unit) { return unit === 'mi' ? km * 0.621371 : km; }
function formatDistance(km: number, unit: Unit) { return `${displayDistance(km, unit).toLocaleString('en-CA', { maximumFractionDigits: 1 })} ${unit}`; }
function monthLabel() { return new Intl.DateTimeFormat('en', { month: 'long', year: 'numeric' }).format(new Date()); }
function readableDate(date: string) { return new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(`${date}T12:00:00`)); }

function AppLogo({ compact = false }: { compact?: boolean }) {
  return <div className="flex items-center gap-3">
    <div className="flex size-10 items-center justify-center rounded-[14px] bg-[hsl(var(--accent))] text-[hsl(var(--primary))] shadow-[3px_3px_0_hsl(var(--primary))]"><CarFront size={21} strokeWidth={2.3} /></div>
    {!compact && <div><p className="display-font text-[17px] font-extrabold leading-none text-[hsl(var(--sidebar-foreground))]">Driver<span className="text-[hsl(var(--accent))]">Logbook</span></p><p className="mt-1 text-[9px] font-bold uppercase tracking-[.22em] text-[hsl(var(--sidebar-foreground)/.55)]">Your pocket co-pilot</p></div>}
  </div>;
}

function NavItem({ href, label, icon: Icon, active }: { href: string; label: string; icon: typeof LayoutDashboard; active: boolean }) {
  return <Link href={href} data-testid={`link-${label.toLowerCase()}`} className={`group flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition-colors ${active ? 'bg-[hsl(var(--sidebar-accent))] text-[hsl(var(--sidebar-foreground))]' : 'text-[hsl(var(--sidebar-foreground)/.62)] hover:bg-[hsl(var(--sidebar-accent)/.7)] hover:text-[hsl(var(--sidebar-foreground))]'}`}>
    <Icon size={18} strokeWidth={active ? 2.3 : 1.8} /><span>{label}</span>{active && <span className="ml-auto size-1.5 rounded-full bg-[hsl(var(--accent))]" />}
  </Link>;
}

function Shell({ children }: { children: ReactNode }) {
  const [location] = useLocation();
  const page = location.startsWith('/settings') ? 'Settings' : location.startsWith('/log') ? 'Logbook' : 'Overview';
  return <div className="app-shell flex">
    <aside className="hidden w-[244px] shrink-0 flex-col bg-[hsl(var(--sidebar))] px-4 py-5 md:flex">
      <div className="px-2"><AppLogo /></div>
      <div className="mt-12 flex flex-1 flex-col gap-1">
        <p className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[.2em] text-[hsl(var(--sidebar-foreground)/.35)]">Workspace</p>
        <NavItem href="/" label="Overview" icon={LayoutDashboard} active={page === 'Overview'} />
        <NavItem href="/log" label="Logbook" icon={ClipboardList} active={page === 'Logbook'} />
        <NavItem href="/settings" label="Settings" icon={SettingsIcon} active={page === 'Settings'} />
      </div>
      <div className="rounded-2xl border border-[hsl(var(--sidebar-border))] bg-[hsl(var(--sidebar-accent)/.55)] p-4">
        <div className="mb-3 flex size-8 items-center justify-center rounded-lg bg-[hsl(var(--accent)/.18)] text-[hsl(var(--accent))]"><CircleHelp size={17} /></div>
        <p className="text-xs font-bold text-[hsl(var(--sidebar-foreground))]">A little less admin.</p>
        <p className="mt-1 text-[11px] leading-4 text-[hsl(var(--sidebar-foreground)/.55)]">Keep moving. We’ll keep the paper trail.</p>
      </div>
    </aside>
    <main className="min-w-0 flex-1 pb-20 md:pb-0">
      <header className="flex h-[76px] items-center justify-between border-b border-[hsl(var(--border))] bg-[hsl(var(--background)/.88)] px-5 backdrop-blur md:px-10">
        <div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[hsl(var(--muted-foreground))]">Driver Logbook</p><h1 className="display-font mt-1 text-xl font-extrabold text-[hsl(var(--foreground))]">{page}</h1></div>
        <div className="flex items-center gap-3"><div className="hidden text-right sm:block"><p className="text-xs font-bold text-[hsl(var(--foreground))]">Ready when you are</p><p className="text-[11px] text-[hsl(var(--muted-foreground))]">Your data stays on this device</p></div><div className="flex size-9 items-center justify-center rounded-full bg-[hsl(var(--secondary))] text-sm font-extrabold text-[hsl(var(--primary))]">DL</div></div>
      </header>
      <div className="mx-auto max-w-[1240px] px-5 py-7 md:px-10 md:py-10">{children}</div>
    </main>
    <nav className="fixed inset-x-0 bottom-0 z-30 flex h-[72px] items-center justify-around border-t border-[hsl(var(--border))] bg-[hsl(var(--card)/.96)] px-5 backdrop-blur md:hidden">
      <NavItem href="/" label="Overview" icon={LayoutDashboard} active={page === 'Overview'} /><NavItem href="/log" label="Logbook" icon={ClipboardList} active={page === 'Logbook'} /><NavItem href="/settings" label="Settings" icon={SettingsIcon} active={page === 'Settings'} />
    </nav>
  </div>;
}

function StatCard({ label, value, helper, icon: Icon, tone = 'dark' }: { label: string; value: string; helper: string; icon: typeof Gauge; tone?: 'dark' | 'gold' | 'mint' }) {
  const styles = tone === 'gold' ? 'bg-[hsl(var(--accent))] text-[hsl(var(--primary))]' : tone === 'mint' ? 'bg-[hsl(166_38%_42%)] text-[hsl(40_35%_96%)]' : 'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]';
  return <div className={`relative overflow-hidden rounded-2xl p-5 ${styles}`} data-testid={`stat-${label.toLowerCase().replaceAll(' ', '-')}`}><div className="flex items-start justify-between"><p className="text-[11px] font-bold uppercase tracking-[.14em] opacity-65">{label}</p><Icon size={19} strokeWidth={1.8} className="opacity-70" /></div><p className="display-font mt-7 text-[30px] font-extrabold tracking-[-.06em]">{value}</p><p className="mt-1 text-xs font-medium opacity-65">{helper}</p><div className="absolute -bottom-8 -right-5 size-28 rounded-full border-[18px] border-current opacity-[.07]" /></div>;
}

function EmptyState({ title = 'No drives logged yet', body = 'Your first entry takes less than a minute. Add the trip you just finished.', onAdd }: { title?: string; body?: string; onAdd?: () => void }) {
  return <div className="soft-grid flex flex-col items-center justify-center rounded-2xl border border-dashed border-[hsl(var(--border))] px-6 py-14 text-center"><div className="mb-4 flex size-12 items-center justify-center rounded-2xl bg-[hsl(var(--accent)/.25)] text-[hsl(var(--primary))]"><Gauge size={23} /></div><h3 className="display-font text-lg font-extrabold text-[hsl(var(--foreground))]">{title}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-[hsl(var(--muted-foreground))]">{body}</p>{onAdd && <button onClick={onAdd} data-testid="button-empty-add-log" className="press mt-6 inline-flex items-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-4 py-3 text-sm font-bold text-[hsl(var(--primary-foreground))] shadow-[0_4px_0_hsl(var(--primary)/.2)]"><Plus size={16} /> Add your first log</button>}</div>;
}

function Dashboard({ logs, settings }: { logs: LogEntry[]; settings: Settings }) {
  const [, setLocation] = useLocation();
  const month = new Date().toISOString().slice(0, 7);
  const current = logs.filter((log) => log.date.startsWith(month));
  const km = current.reduce((sum, log) => sum + log.distanceKm, 0);
  const fuel = current.reduce((sum, log) => sum + log.fuelLiters, 0);
  const cost = current.reduce((sum, log) => sum + log.fuelCost, 0);
  const recent = [...logs].sort((a, b) => b.date.localeCompare(a.date) || b.createdAt.localeCompare(a.createdAt)).slice(0, 4);
  const firstName = settings.driverName.trim().split(' ')[0] || 'Driver';
  return <div className="space-y-8">
    <section className="fade-up flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mono-font text-xs font-medium text-[hsl(var(--muted-foreground))]">{monthLabel()} / at a glance</p><h2 className="display-font mt-2 max-w-xl text-[clamp(2rem,5vw,3.5rem)] font-extrabold leading-[.98] text-[hsl(var(--foreground))]">Keep your miles<br /><span className="text-[hsl(166_38%_42%)]">working for you.</span></h2><p className="mt-4 max-w-md text-sm leading-6 text-[hsl(var(--muted-foreground))]">Good records make tax time quieter. Log a drive while it’s still fresh.</p></div><button onClick={() => setLocation('/log?new=1')} data-testid="button-add-log-dashboard" className="press group flex shrink-0 items-center justify-center gap-3 rounded-xl bg-[hsl(var(--primary))] px-5 py-3.5 text-sm font-bold text-[hsl(var(--primary-foreground))] shadow-[0_4px_0_hsl(var(--primary)/.25)]"><Plus size={18} className="transition-transform group-hover:rotate-90" /> Add a log <ArrowRight size={16} /></button></section>
    <section className="fade-up fade-up-delay-1 grid gap-3 sm:grid-cols-3"><StatCard label="Distance" value={formatDistance(km, settings.unit)} helper="this month" icon={BarChart3} /><StatCard label="Fuel used" value={`${fuel.toLocaleString('en-CA', { maximumFractionDigits: 1 })} L`} helper={`${current.length} ${current.length === 1 ? 'fill-up' : 'fill-ups'} recorded`} icon={Fuel} tone="gold" /><StatCard label="Fuel cost" value={formatMoney(cost, settings.currency)} helper="tracked this month" icon={DollarSign} tone="mint" /></section>
    <section className="fade-up fade-up-delay-2 grid gap-5 lg:grid-cols-[1.35fr_.65fr]">
      <div className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 md:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.15em] text-[hsl(var(--muted-foreground))]">Recent activity</p><h3 className="display-font mt-1 text-xl font-extrabold">Your latest logs</h3></div><Link href="/log" data-testid="link-view-all-logs" className="flex items-center gap-1 text-xs font-bold text-[hsl(var(--primary))] hover:text-[hsl(166_38%_42%)]">View all <ArrowRight size={14} /></Link></div>{recent.length === 0 ? <EmptyState onAdd={() => setLocation('/log?new=1')} /> : <div className="space-y-2">{recent.map((log) => <LogRow key={log.id} log={log} settings={settings} onClick={() => setLocation(`/log?view=${log.id}`)} />)}</div>}</div>
      <div className="relative overflow-hidden rounded-2xl bg-[hsl(var(--primary))] p-6 text-[hsl(var(--primary-foreground))]"><div className="relative z-10"><div className="mb-8 flex items-center justify-between"><div className="flex size-10 items-center justify-center rounded-xl bg-[hsl(var(--accent)/.16)] text-[hsl(var(--accent))]"><Zap size={20} /></div><span className="mono-font text-[10px] uppercase tracking-[.18em] opacity-45">quick note</span></div><p className="display-font text-2xl font-extrabold leading-tight">Hey, {firstName}.<br />Small entries add up.</p><p className="mt-3 text-sm leading-6 opacity-65">A photo of your odometer or receipt now can save a search through old camera rolls later.</p><Link href="/settings" data-testid="link-dashboard-settings" className="mt-8 inline-flex items-center gap-2 text-xs font-bold text-[hsl(var(--accent))]">Tune your preferences <ArrowRight size={14} /></Link></div><div className="absolute -bottom-14 -right-10 size-52 rounded-full border-[32px] border-[hsl(var(--accent)/.12)]" /><div className="absolute -right-1 top-20 size-20 rounded-full border border-[hsl(var(--accent)/.18)]" /></div>
    </section>
  </div>;
}

function LogRow({ log, settings, onClick }: { log: LogEntry; settings: Settings; onClick: () => void }) {
  return <button onClick={onClick} data-testid={`row-log-${log.id}`} className="press group flex w-full items-center gap-3 rounded-xl border border-transparent px-3 py-3 text-left hover:border-[hsl(var(--border))] hover:bg-[hsl(var(--background))]"><div className="flex size-10 shrink-0 flex-col items-center justify-center rounded-xl bg-[hsl(var(--secondary))] text-[hsl(var(--primary))]"><span className="text-[10px] font-bold uppercase">{new Intl.DateTimeFormat('en', { month: 'short' }).format(new Date(`${log.date}T12:00:00`))}</span><span className="display-font text-lg font-extrabold leading-4">{new Date(`${log.date}T12:00:00`).getDate()}</span></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-[hsl(var(--foreground))]">{log.station || log.platform} <span className="ml-1 rounded-md bg-[hsl(var(--muted))] px-1.5 py-0.5 text-[10px] font-bold text-[hsl(var(--muted-foreground))]">{log.platform}</span></p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{formatDistance(log.distanceKm, settings.unit)} · {log.fuelLiters} L</p></div><div className="text-right"><p className="mono-font text-sm font-medium text-[hsl(var(--foreground))]">{formatMoney(log.fuelCost, settings.currency)}</p><ArrowRight size={14} className="ml-auto mt-1 text-[hsl(var(--muted-foreground))] opacity-0 transition-opacity group-hover:opacity-100" /></div></button>;
}

function PhotoPicker({ label, value, onChange, icon: Icon }: { label: string; value?: string; onChange: (value?: string) => void; icon: typeof Gauge }) {
  const inputRef = useRef<HTMLInputElement>(null);
  const handleFile = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => onChange(String(reader.result)); reader.readAsDataURL(file); };
  return <div><p className="mb-2 text-xs font-bold text-[hsl(var(--foreground))]">{label}</p>{value ? <div className="group relative overflow-hidden rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--secondary))]"><img src={value} alt={label} className="h-28 w-full object-cover" /><button type="button" onClick={() => onChange(undefined)} data-testid={`button-remove-${label.toLowerCase().replaceAll(' ', '-')}`} className="absolute right-2 top-2 flex size-7 items-center justify-center rounded-lg bg-[hsl(var(--primary)/.85)] text-white"><X size={14} /></button></div> : <button type="button" onClick={() => inputRef.current?.click()} data-testid={`button-upload-${label.toLowerCase().replaceAll(' ', '-')}`} className="press flex h-28 w-full flex-col items-center justify-center gap-2 rounded-xl border border-dashed border-[hsl(var(--input))] bg-[hsl(var(--background))] text-[hsl(var(--muted-foreground))] hover:border-[hsl(var(--primary))] hover:text-[hsl(var(--primary))]"><Icon size={22} strokeWidth={1.7} /><span className="text-[11px] font-bold">Tap to add photo</span><span className="text-[10px]">Camera or library</span></button>}<input ref={inputRef} className="hidden" type="file" accept="image/*" capture="environment" onChange={(event) => handleFile(event.target.files?.[0])} /></div>;
}

const emptyForm = { date: today(), startOdometer: '', endOdometer: '', fuelLiters: '', fuelCost: '', station: '', platform: 'Uber' as Platform, notes: '', odometerPhoto: undefined as string | undefined, receiptPhoto: undefined as string | undefined };
function LogForm({ initial, onSave, onCancel }: { initial?: LogEntry; onSave: (log: LogEntry) => void; onCancel: () => void }) {
  const [form, setForm] = useState(() => initial ? { date: initial.date, startOdometer: String(initial.startOdometer), endOdometer: String(initial.endOdometer), fuelLiters: String(initial.fuelLiters), fuelCost: String(initial.fuelCost), station: initial.station, platform: initial.platform, notes: initial.notes, odometerPhoto: initial.odometerPhoto, receiptPhoto: initial.receiptPhoto } : emptyForm);
  const set = (key: keyof typeof form, value: string | undefined) => setForm((current) => ({ ...current, [key]: value }));
  const distance = Math.max(0, (Number(form.endOdometer) || 0) - (Number(form.startOdometer) || 0));
  const valid = Boolean(form.date && Number(form.endOdometer) >= Number(form.startOdometer) && Number(form.endOdometer) > 0);
  const submit = (event: FormEvent) => { event.preventDefault(); if (!valid) return; onSave({ id: initial?.id || makeId(), date: form.date, startOdometer: Number(form.startOdometer), endOdometer: Number(form.endOdometer), distanceKm: distance, fuelLiters: Number(form.fuelLiters) || 0, fuelCost: Number(form.fuelCost) || 0, station: form.station.trim(), platform: form.platform, notes: form.notes.trim(), odometerPhoto: form.odometerPhoto, receiptPhoto: form.receiptPhoto, createdAt: initial?.createdAt || new Date().toISOString() }); };
  return <form onSubmit={submit} className="space-y-5">
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Date"><input data-testid="input-log-date" type="date" value={form.date} onChange={(e) => set('date', e.target.value)} /></Field><Field label="Platform"><select data-testid="select-log-platform" value={form.platform} onChange={(e) => set('platform', e.target.value)}>{(['Uber', 'Lyft', 'Both', 'Personal'] as Platform[]).map((item) => <option key={item}>{item}</option>)}</select></Field></div>
    <div><p className="mb-2 text-xs font-bold text-[hsl(var(--foreground))]">Odometer reading <span className="font-normal text-[hsl(var(--muted-foreground))]">· km</span></p><div className="grid grid-cols-2 gap-3"><Field label="Start"><input data-testid="input-start-odometer" inputMode="decimal" type="number" min="0" step="0.1" placeholder="12,480" value={form.startOdometer} onChange={(e) => set('startOdometer', e.target.value)} /></Field><Field label="End"><input data-testid="input-end-odometer" inputMode="decimal" type="number" min="0" step="0.1" placeholder="12,532" value={form.endOdometer} onChange={(e) => set('endOdometer', e.target.value)} /></Field></div>{form.endOdometer && <p className={`mt-2 text-xs font-bold ${valid ? 'text-[hsl(166_38%_42%)]' : 'text-[hsl(var(--destructive))]'}`}>{valid ? `${distance.toLocaleString()} km logged` : 'End reading must be greater than start'}</p>}</div>
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Fuel added · litres"><input data-testid="input-fuel-liters" inputMode="decimal" type="number" min="0" step="0.01" placeholder="42.5" value={form.fuelLiters} onChange={(e) => set('fuelLiters', e.target.value)} /></Field><Field label="Fuel cost"><input data-testid="input-fuel-cost" inputMode="decimal" type="number" min="0" step="0.01" placeholder="78.40" value={form.fuelCost} onChange={(e) => set('fuelCost', e.target.value)} /></Field></div>
    <Field label="Station or location (optional)"><input data-testid="input-station" placeholder="Petro-Canada · Main & 4th" value={form.station} onChange={(e) => set('station', e.target.value)} /></Field>
    <Field label="Notes (optional)"><textarea data-testid="input-log-notes" rows={3} placeholder="Anything worth remembering about this drive..." value={form.notes} onChange={(e) => set('notes', e.target.value)} /></Field>
    <div className="grid gap-3 sm:grid-cols-2"><PhotoPicker label="Odometer photo" value={form.odometerPhoto} onChange={(value) => set('odometerPhoto', value)} icon={Gauge} /><PhotoPicker label="Fuel receipt photo" value={form.receiptPhoto} onChange={(value) => set('receiptPhoto', value)} icon={Receipt} /></div>
    <div className="flex gap-3 border-t border-[hsl(var(--border))] pt-5"><button type="button" onClick={onCancel} data-testid="button-cancel-log" className="press flex-1 rounded-xl border border-[hsl(var(--border))] px-4 py-3 text-sm font-bold text-[hsl(var(--foreground))]">Cancel</button><button type="submit" disabled={!valid} data-testid="button-save-log" className="press flex-[1.5] rounded-xl bg-[hsl(var(--primary))] px-4 py-3 text-sm font-bold text-[hsl(var(--primary-foreground))] disabled:cursor-not-allowed disabled:opacity-40">{initial ? 'Save changes' : 'Save log'}</button></div>
  </form>;
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-xs font-bold text-[hsl(var(--muted-foreground))]">{label}<div className="mt-2 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-[hsl(var(--input))] [&_input]:bg-[hsl(var(--background))] [&_input]:px-3.5 [&_input]:py-3 [&_input]:text-sm [&_input]:font-medium [&_input]:text-[hsl(var(--foreground))] [&_input]:outline-none [&_input]:transition-colors [&_input]:focus:border-[hsl(var(--primary))] [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-[hsl(var(--input))] [&_select]:bg-[hsl(var(--background))] [&_select]:px-3.5 [&_select]:py-3 [&_select]:text-sm [&_select]:font-medium [&_select]:text-[hsl(var(--foreground))] [&_textarea]:w-full [&_textarea]:resize-none [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-[hsl(var(--input))] [&_textarea]:bg-[hsl(var(--background))] [&_textarea]:px-3.5 [&_textarea]:py-3 [&_textarea]:text-sm [&_textarea]:font-medium [&_textarea]:text-[hsl(var(--foreground))] [&_textarea]:outline-none [&_textarea]:focus:border-[hsl(var(--primary))]">{children}</div></label>; }

function Modal({ title, children, onClose, wide = false }: { title: string; children: ReactNode; onClose: () => void; wide?: boolean }) {
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-[hsl(var(--primary)/.48)] p-0 backdrop-blur-[2px] sm:items-center sm:p-5" role="dialog" aria-modal="true"><div className={`max-h-[92dvh] w-full overflow-y-auto rounded-t-[24px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 shadow-2xl sm:rounded-[24px] sm:p-7 ${wide ? 'max-w-2xl' : 'max-w-lg'}`}><div className="mb-6 flex items-start justify-between"><div><p className="mono-font text-[10px] font-medium uppercase tracking-[.18em] text-[hsl(var(--muted-foreground))]">Driver Logbook</p><h2 className="display-font mt-1 text-2xl font-extrabold">{title}</h2></div><button onClick={onClose} data-testid="button-close-modal" className="press flex size-9 items-center justify-center rounded-xl bg-[hsl(var(--secondary))] text-[hsl(var(--foreground))]"><X size={17} /></button></div>{children}</div></div>;
}

function Detail({ log, settings, onEdit, onDelete, onClose }: { log: LogEntry; settings: Settings; onEdit: () => void; onDelete: () => void; onClose: () => void }) {
  return <Modal title={readableDate(log.date)} onClose={onClose} wide><div className="grid gap-6 sm:grid-cols-[1fr_1fr]"><div><div className="rounded-2xl bg-[hsl(var(--primary))] p-5 text-[hsl(var(--primary-foreground))]"><div className="flex items-center justify-between"><span className="rounded-lg bg-[hsl(var(--accent)/.2)] px-2.5 py-1 text-[11px] font-bold text-[hsl(var(--accent))]">{log.platform}</span><span className="mono-font text-xs opacity-60">{formatDistance(log.distanceKm, settings.unit)}</span></div><p className="display-font mt-7 text-4xl font-extrabold">{formatMoney(log.fuelCost, settings.currency)}</p><p className="mt-1 text-xs opacity-60">fuel cost recorded</p></div><div className="mt-4 grid grid-cols-2 gap-2"><DetailStat label="Fuel" value={`${log.fuelLiters} L`} /><DetailStat label="Station" value={log.station || '—'} /></div><div className="mt-2 grid grid-cols-2 gap-2"><DetailStat label="Start" value={log.startOdometer.toLocaleString()} /><DetailStat label="End" value={log.endOdometer.toLocaleString()} /></div></div><div className="space-y-3">{log.notes && <div className="rounded-xl bg-[hsl(var(--secondary))] p-4"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[hsl(var(--muted-foreground))]">Notes</p><p className="mt-2 text-sm leading-6">{log.notes}</p></div>} {(log.odometerPhoto || log.receiptPhoto) ? <div className="grid grid-cols-2 gap-2">{log.odometerPhoto && <img src={log.odometerPhoto} alt="Odometer" className="h-32 w-full rounded-xl object-cover" />}{log.receiptPhoto && <img src={log.receiptPhoto} alt="Fuel receipt" className="h-32 w-full rounded-xl object-cover" />}</div> : <div className="flex h-32 flex-col items-center justify-center rounded-xl border border-dashed border-[hsl(var(--border))] text-center text-xs text-[hsl(var(--muted-foreground))]"><FileImage size={20} className="mb-2 opacity-60" />No photos attached</div>}<div className="flex gap-2 pt-2"><button onClick={onEdit} data-testid="button-edit-log-detail" className="press flex flex-1 items-center justify-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-3 py-3 text-xs font-bold text-[hsl(var(--primary-foreground))]"><Pencil size={14} /> Edit log</button><button onClick={onDelete} data-testid="button-delete-log-detail" className="press flex size-11 items-center justify-center rounded-xl border border-[hsl(var(--border))] text-[hsl(var(--destructive))]"><Trash2 size={16} /></button></div></div></div></Modal>;
}
function DetailStat({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-[hsl(var(--muted-foreground))]">{label}</p><p className="mt-1 truncate text-sm font-bold">{value}</p></div>; }

function Logbook({ logs, settings, updateLogs }: { logs: LogEntry[]; settings: Settings; updateLogs: (logs: LogEntry[]) => void }) {
  const [location, setLocation] = useLocation();
  const [query, setQuery] = useState('');
  const [platform, setPlatform] = useState<'All' | Platform>('All');
  const [modal, setModal] = useState<'new' | 'edit' | 'detail' | null>(null);
  const [selected, setSelected] = useState<LogEntry | undefined>();
  const [flash, setFlash] = useState('');
  useEffect(() => { const params = new URLSearchParams(location.split('?')[1]); const viewId = params.get('view'); if (params.get('new') === '1') setModal('new'); if (viewId) { setSelected(logs.find((log) => log.id === viewId)); setModal('detail'); } }, [location, logs]);
  const filtered = useMemo(() => [...logs].sort((a, b) => b.date.localeCompare(a.date)).filter((log) => (platform === 'All' || log.platform === platform) && `${log.station} ${log.platform} ${log.notes}`.toLowerCase().includes(query.toLowerCase())), [logs, platform, query]);
  const close = () => { setModal(null); setSelected(undefined); if (location.includes('?')) setLocation('/log'); };
  const save = (entry: LogEntry) => { updateLogs(logs.some((log) => log.id === entry.id) ? logs.map((log) => log.id === entry.id ? entry : log) : [entry, ...logs]); setFlash(logs.some((log) => log.id === entry.id) ? 'Log updated' : 'Log saved'); close(); window.setTimeout(() => setFlash(''), 2200); };
  const deleteLog = (entry: LogEntry) => { if (!window.confirm('Delete this log? This cannot be undone.')) return; updateLogs(logs.filter((log) => log.id !== entry.id)); setFlash('Log deleted'); close(); window.setTimeout(() => setFlash(''), 2200); };
  return <div className="space-y-7">
    <section className="fade-up flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mono-font text-xs text-[hsl(var(--muted-foreground))]">Every stop, accounted for</p><h2 className="display-font mt-2 text-3xl font-extrabold">Your logbook</h2><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">{logs.length} {logs.length === 1 ? 'entry' : 'entries'} stored on this device.</p></div><button onClick={() => setModal('new')} data-testid="button-add-log" className="press flex items-center justify-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-4 py-3 text-sm font-bold text-[hsl(var(--primary-foreground))]"><Plus size={17} /> Add a log</button></section>
    {flash && <div data-testid="status-log-feedback" className="fade-up fixed bottom-24 left-1/2 z-40 flex -translate-x-1/2 items-center gap-2 rounded-full bg-[hsl(var(--primary))] px-4 py-2.5 text-xs font-bold text-[hsl(var(--primary-foreground))] shadow-lg md:bottom-7"><Check size={15} className="text-[hsl(var(--accent))]" />{flash}</div>}
    <section className="fade-up fade-up-delay-1 rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-4"><div className="flex flex-col gap-3 md:flex-row"><label className="relative flex-1"><Search size={17} className="absolute left-3 top-3.5 text-[hsl(var(--muted-foreground))]" /><input data-testid="input-search-logs" type="search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search station, notes or platform..." className="w-full rounded-xl border border-[hsl(var(--input))] bg-[hsl(var(--background))] py-3 pl-10 pr-4 text-sm outline-none focus:border-[hsl(var(--primary))]" /></label><div className="relative"><select data-testid="select-filter-platform" value={platform} onChange={(e) => setPlatform(e.target.value as typeof platform)} className="w-full appearance-none rounded-xl border border-[hsl(var(--input))] bg-[hsl(var(--background))] py-3 pl-3 pr-9 text-sm font-semibold outline-none md:w-40"><option>All</option><option>Uber</option><option>Lyft</option><option>Both</option><option>Personal</option></select><ChevronDown size={15} className="pointer-events-none absolute right-3 top-3.5 text-[hsl(var(--muted-foreground))]" /></div></div></section>
    <section className="fade-up fade-up-delay-2">{filtered.length === 0 ? <EmptyState title={logs.length ? 'No matching logs' : 'Your logbook is ready'} body={logs.length ? 'Try a different station, note, or platform filter.' : 'Start with the trip you just finished. We’ll keep every detail close at hand.'} onAdd={logs.length ? undefined : () => setModal('new')} /> : <div className="space-y-2">{filtered.map((log) => <div key={log.id} className="group rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-4 transition-shadow hover:shadow-md"><div className="flex items-center gap-3"><button onClick={() => { setSelected(log); setModal('detail'); }} data-testid={`button-view-log-${log.id}`} className="flex min-w-0 flex-1 items-center gap-3 text-left"><div className="flex size-11 shrink-0 flex-col items-center justify-center rounded-xl bg-[hsl(var(--secondary))] text-[hsl(var(--primary))]"><span className="text-[10px] font-bold uppercase">{new Intl.DateTimeFormat('en', { month: 'short' }).format(new Date(`${log.date}T12:00:00`))}</span><span className="display-font text-lg font-extrabold leading-4">{new Date(`${log.date}T12:00:00`).getDate()}</span></div><div className="min-w-0"><p className="truncate text-sm font-bold">{log.station || 'Unlabeled stop'}</p><p className="mt-1 truncate text-xs text-[hsl(var(--muted-foreground))]">{log.platform} · {formatDistance(log.distanceKm, settings.unit)} · {log.fuelLiters} L</p></div></button><div className="hidden text-right sm:block"><p className="mono-font text-sm font-medium">{formatMoney(log.fuelCost, settings.currency)}</p><p className="mt-1 text-[10px] text-[hsl(var(--muted-foreground))]">{log.odometerPhoto || log.receiptPhoto ? 'Photos attached' : 'No photos'}</p></div><button onClick={() => { setSelected(log); setModal('edit'); }} data-testid={`button-edit-log-${log.id}`} className="press flex size-9 items-center justify-center rounded-lg text-[hsl(var(--muted-foreground))] hover:bg-[hsl(var(--secondary))] hover:text-[hsl(var(--primary))]"><Pencil size={15} /></button><button onClick={() => deleteLog(log)} data-testid={`button-delete-log-${log.id}`} className="press flex size-9 items-center justify-center rounded-lg text-[hsl(var(--muted-foreground))] hover:bg-[hsl(5_63%_52%/.1)] hover:text-[hsl(var(--destructive))]"><Trash2 size={15} /></button></div></div>)}</div>}</section>
    {modal === 'new' && <Modal title="Add a log" onClose={close}><LogForm onSave={save} onCancel={close} /></Modal>}{modal === 'edit' && selected && <Modal title="Edit this log" onClose={close}><LogForm initial={selected} onSave={save} onCancel={close} /></Modal>}{modal === 'detail' && selected && <Detail log={selected} settings={settings} onEdit={() => setModal('edit')} onDelete={() => deleteLog(selected)} onClose={close} />}
  </div>;
}

function SettingsPage({ settings, updateSettings, logs, updateLogs }: { settings: Settings; updateSettings: (settings: Settings) => void; logs: LogEntry[]; updateLogs: (logs: LogEntry[]) => void }) {
  const [draft, setDraft] = useState(settings);
  const [flash, setFlash] = useState('');
  useEffect(() => setDraft(settings), [settings]);
  const save = () => { updateSettings(draft); setFlash('Preferences saved'); window.setTimeout(() => setFlash(''), 2200); };
  const exportData = () => { const blob = new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), settings, logs }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `driver-logbook-${today()}.json`; link.click(); URL.revokeObjectURL(url); setFlash('Export downloaded'); window.setTimeout(() => setFlash(''), 2200); };
  const reset = () => { if (window.confirm('Reset Driver Logbook? All logs and preferences on this device will be deleted.')) { updateLogs([]); updateSettings(defaultSettings); setDraft(defaultSettings); setFlash('All local data reset'); window.setTimeout(() => setFlash(''), 2200); } };
  return <div className="mx-auto max-w-3xl space-y-7">
    <section className="fade-up"><p className="mono-font text-xs text-[hsl(var(--muted-foreground))]">Personalize your co-pilot</p><h2 className="display-font mt-2 text-3xl font-extrabold">Settings</h2><p className="mt-2 text-sm leading-6 text-[hsl(var(--muted-foreground))]">A few preferences make every entry feel like yours. Everything is saved locally.</p></section>
    {flash && <div data-testid="status-settings-feedback" className="fade-up fixed bottom-24 left-1/2 z-40 flex -translate-x-1/2 items-center gap-2 rounded-full bg-[hsl(var(--primary))] px-4 py-2.5 text-xs font-bold text-[hsl(var(--primary-foreground))] shadow-lg md:bottom-7"><Check size={15} className="text-[hsl(var(--accent))]" />{flash}</div>}
    <section className="fade-up fade-up-delay-1 overflow-hidden rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))]"><div className="border-b border-[hsl(var(--border))] bg-[hsl(var(--secondary)/.55)] px-5 py-4"><p className="text-xs font-bold uppercase tracking-[.14em]">Driver profile</p></div><div className="space-y-5 p-5 md:p-6"><Field label="Your name (optional)"><input data-testid="input-driver-name" value={draft.driverName} placeholder="How should we greet you?" onChange={(e) => setDraft({ ...draft, driverName: e.target.value })} /></Field><div className="grid gap-5 sm:grid-cols-2"><div><p className="mb-2 text-xs font-bold text-[hsl(var(--muted-foreground))]">Distance unit</p><div className="grid grid-cols-2 gap-2">{(['km', 'mi'] as Unit[]).map((unit) => <button key={unit} onClick={() => setDraft({ ...draft, unit })} data-testid={`button-unit-${unit}`} className={`press rounded-xl border px-4 py-3 text-sm font-bold ${draft.unit === unit ? 'border-[hsl(var(--primary))] bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]' : 'border-[hsl(var(--border))] bg-[hsl(var(--background))] text-[hsl(var(--muted-foreground))]'}`}>{unit === 'km' ? 'Kilometres' : 'Miles'}<span className="mt-1 block text-[10px] font-medium opacity-65">{unit}</span></button>)}</div></div><div><p className="mb-2 text-xs font-bold text-[hsl(var(--muted-foreground))]">Currency for fuel</p><div className="grid grid-cols-2 gap-2">{(['CAD', 'USD'] as Currency[]).map((currency) => <button key={currency} onClick={() => setDraft({ ...draft, currency })} data-testid={`button-currency-${currency.toLowerCase()}`} className={`press rounded-xl border px-4 py-3 text-sm font-bold ${draft.currency === currency ? 'border-[hsl(var(--primary))] bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]' : 'border-[hsl(var(--border))] bg-[hsl(var(--background))] text-[hsl(var(--muted-foreground))]'}`}>{currency}<span className="mt-1 block text-[10px] font-medium opacity-65">{currency === 'CAD' ? 'Canadian dollar' : 'US dollar'}</span></button>)}</div></div></div><button onClick={save} data-testid="button-save-settings" className="press flex items-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-4 py-3 text-sm font-bold text-[hsl(var(--primary-foreground))]"><Check size={16} /> Save preferences</button></div></section>
    <section className="fade-up fade-up-delay-2 overflow-hidden rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))]"><div className="border-b border-[hsl(var(--border))] bg-[hsl(var(--secondary)/.55)] px-5 py-4"><p className="text-xs font-bold uppercase tracking-[.14em]">Your data</p></div><div className="divide-y divide-[hsl(var(--border))]"><button onClick={exportData} data-testid="button-export-data" className="press flex w-full items-center gap-4 px-5 py-5 text-left hover:bg-[hsl(var(--background))]"><div className="flex size-10 items-center justify-center rounded-xl bg-[hsl(166_38%_42%/.12)] text-[hsl(166_38%_42%)]"><Download size={18} /></div><div className="flex-1"><p className="text-sm font-bold">Export a backup</p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Download {logs.length} {logs.length === 1 ? 'log' : 'logs'} and your preferences as JSON.</p></div><ArrowDownToLine size={17} className="text-[hsl(var(--muted-foreground))]" /></button><button onClick={reset} data-testid="button-reset-data" className="press flex w-full items-center gap-4 px-5 py-5 text-left hover:bg-[hsl(5_63%_52%/.05)]"><div className="flex size-10 items-center justify-center rounded-xl bg-[hsl(5_63%_52%/.1)] text-[hsl(var(--destructive))]"><RotateCcw size={18} /></div><div className="flex-1"><p className="text-sm font-bold text-[hsl(var(--destructive))]">Reset local data</p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Permanently remove all logs from this device.</p></div><Trash2 size={17} className="text-[hsl(var(--destructive))]" /></button></div></section>
    <p className="flex items-center justify-center gap-2 pb-4 text-center text-[11px] text-[hsl(var(--muted-foreground))]"><Upload size={13} /> Private by default · no account or cloud required</p>
  </div>;
}

function NotFound() { return <div className="flex min-h-[60dvh] flex-col items-center justify-center text-center"><p className="mono-font text-xs text-[hsl(var(--muted-foreground))]">404 / wrong turn</p><h2 className="display-font mt-3 text-3xl font-extrabold">That road ends here.</h2><Link href="/" data-testid="link-back-overview" className="mt-5 rounded-xl bg-[hsl(var(--primary))] px-4 py-3 text-sm font-bold text-[hsl(var(--primary-foreground))]">Back to overview</Link></div>; }

function Router() {
  const [logs, setLogs] = useStored<LogEntry[]>(LOGS_KEY, []);
  const [settings, setSettings] = useStored<Settings>(SETTINGS_KEY, defaultSettings);
  return <Shell><Switch><Route path="/"><Dashboard logs={logs} settings={settings} /></Route><Route path="/log"><Logbook logs={logs} settings={settings} updateLogs={setLogs} /></Route><Route path="/settings"><SettingsPage settings={settings} updateSettings={setSettings} logs={logs} updateLogs={setLogs} /></Route><Route component={NotFound} /></Switch></Shell>;
}

function App() { return <QueryClientProvider client={queryClient}><TooltipProvider><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, '')}><ErrorBoundary><Router /></ErrorBoundary></WouterRouter><Toaster /></TooltipProvider></QueryClientProvider>; }
export default App;
